baseURL = "https://cynmit05.github.io/"
title = "Cynmit"
theme = ["PaperMod"]

paginate = 5

defaultContentLanguage = "zh-cn"

locale = "zh-cn"

[languages.zh-cn]
label = "Chinese"
locale = "zh-cn"
direction = "ltr"
weight = 1

[[menu.main]]
identifier = "home"
name = "首页"
url = "/"
weight = 1

[[menu.main]]
identifier = "learn"
name = "学习"
url = "/learn/"
weight = 2

[[menu.main]]
identifier = "practice"
name = "实战"
url = "/practice/"
weight = 3

[[menu.main]]
identifier = "plan"
name = "计划"
url = "/plan/"
weight = 4

[[menu.main]]
identifier = "share"
name = "分享"
url = "/share/"
weight = 5

[[menu.main]]
identifier = "games"
name = "小游戏"
url = "/games/"
weight = 6

[[menu.main]]
identifier = "whisper"
name = "碎碎念"
url = "/whisper/"
weight = 7

[[menu.main]]
identifier = "guestbook"
name = "留言板"
url = "/guestbook/"
weight = 8

[params]
env = "production"
description = "记录学习、思考与生活。"
author = "Cynmit"
defaultTheme = "dark"
disableThemeToggle = true
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = false
ShowCodeCopyButtons = true
ShowWordCount = false
ShowRssButtonInSectionTermList = false
UseHugoToc = true
comments = true

[params.giscus]
repo = "Cynmit05/Cynmit05.github.io"
repoId = "1286815776"
category = "Announcements"
categoryId = "DIC_kwDOTLNAIM4DAWc8"

[params.profileMode]
enabled = true
title = "Cynmit"
subtitle = "记录学习、思考与生活"
imageUrl = ""
imageWidth = 120
imageHeight = 120

[[params.socialIcons]]
name = "github"
url = "https://github.com/cynmit05"

[[params.socialIcons]]
name = "email"
url = "mailto:2678600304@qq.com"

[params.footer]
text = "LI FU JUN · 2678600304@qq.com"

[params.assets]
disableHLJS = true

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1000
threshold = 0.4
minMatchCharLength = 0
keys = ["title", "permalink", "summary", "content"]

[outputs]
home = ["HTML", "RSS", "JSON"]

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

ignoreLogs = ["warning-goldmark-raw-html"]
